### PR TITLE
Show suggested dicussions as links, when links are enabled in the runtime

### PR DESCRIPTION
**Pull request by arkose**
Here's the pull request for the library links for suggestions code I posted in the NPC Conversations thread at IntFiction.

### CODE REVIEW

**Review by hlship — COMMENTED** [review]
It feels like there should be a way to abstract the `(if) (library links enabled) ...` logic into its own predicate.

**Comment by hlship** [comment]
Please note that by providing this PR, you are assigning copyright for the provided materials to the repository owner (me, Howard Lewis Ship).

**Comment by arkose** [comment]
Yes, no issue with the copyright assignment for this or future push requests.

**Comment by hlship** [comment]
Just a formality.

Also, I'd like to hold off until after the upgrade to dialog 0i/01, since that may change how the links are generated.

**Review by hlship — APPROVED** [review]

**Pull request merged**
